"""Regenerate the shared WordPiece golden vectors.

Small vocabs get embedded into the JSON; a real vocab.txt is referenced by
filename instead (put a copy next to the JSON in tests/data/ so both test
suites can load it). Phrases run through the normalizer first, mirroring what
the tokenizer sees at inference time.
"""

import argparse
import json
from pathlib import Path

from .normalize import normalize
from .wordpiece import WordPieceTokenizer

INLINE_VOCAB_LIMIT = 1000

DEFAULT_PHRASES = [
    "skip meals wake up thinner",
    "st4rv1ng is a lifestyle",
    "only ⭐ will give you the body",
    "trying a new pasta recipe tonight",
    "cw 52 gw 44",
    "recovery win: had breakfast with my family",
    "рurgе the guilt away",
    "",
]


def build(vocab_path: Path, phrases: list, max_len: int) -> dict:
    vocab_lines = vocab_path.read_text().splitlines()
    tokenizer = WordPieceTokenizer(vocab_lines, max_len=max_len)

    cases = []
    for phrase in phrases:
        text = normalize(phrase)
        ids, mask = tokenizer.encode(text)
        cases.append({"text": text, "ids": ids[: sum(mask)]})

    golden = {
        "description": (
            "Shared WordPiece golden vectors, generated by samind_ml.make_goldens. "
            "Consumed by ml/tests/test_wordpiece_golden.py and android "
            "GoldenWordPieceTest.kt. 'ids' is the unpadded token sequence."
        ),
        "max_len": max_len,
    }
    if len(vocab_lines) <= INLINE_VOCAB_LIMIT:
        golden["vocab"] = vocab_lines
    else:
        golden["vocab_file"] = vocab_path.name
    golden["cases"] = cases
    return golden


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--vocab", required=True, help="vocab.txt, one token per line")
    parser.add_argument("--phrases", help="file with one raw phrase per line")
    parser.add_argument("--max-len", type=int, default=128)
    parser.add_argument("--out", default="tests/data/golden_wordpiece.json")
    args = parser.parse_args()

    phrases = (
        Path(args.phrases).read_text().splitlines() if args.phrases else DEFAULT_PHRASES
    )
    golden = build(Path(args.vocab), phrases, args.max_len)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(golden, ensure_ascii=False, indent=2) + "\n")
    print(f"wrote {out} ({len(golden['cases'])} cases)")
    if "vocab_file" in golden:
        print(f"reminder: copy {args.vocab} to {out.parent / golden['vocab_file']}")


if __name__ == "__main__":
    main()
